# Generated by Django 5.2.6 on 2025-09-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_add_status_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='programexecution',
            new_name='problems_pr_student_72291d_idx',
            old_name='problems_pr_student__idx',
        ),
        migrations.AlterField(
            model_name='programexecution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
