# Generated by Django 5.2.6 on 2025-09-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_problems_pr_student__idx_problems_pr_student_72291d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexecution',
            name='execution_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
