# Generated by Django 5.2.6 on 2025-09-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRepairPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('model_id', models.CharField(max_length=100)),
                ('model_temperature', models.FloatField()),
                ('model_n', models.IntegerField()),
                ('n_correct_repairs', models.IntegerField()),
                ('best_repair', models.TextField()),
                ('whole_llm_response', models.TextField()),
                ('llm_waiting_seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_id', models.CharField(max_length=100)),
                ('student_program', models.TextField()),
                ('hint_type', models.CharField(max_length=20)),
                ('student_program_output', models.TextField(null=True)),
                ('expected_output', models.TextField(null=True)),
                ('run_time', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_program', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('program_output', models.TextField()),
                ('run_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.programrepairphase')),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection_question', models.TextField()),
                ('reflection_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.request')),
            ],
        ),
        migrations.AddField(
            model_name='programrepairphase',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.request', unique=True),
        ),
        migrations.CreateModel(
            name='HintGenerationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('model_id', models.CharField(max_length=100)),
                ('model_temperature', models.FloatField()),
                ('whole_llm_response', models.TextField()),
                ('llm_waiting_seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.request', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField()),
                ('job_finished_successfully', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.request')),
            ],
        ),
    ]
