# Generated by Django 5.2.6 on 2025-09-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='expected_output',
        ),
    ]
