# Generated by Django 5.2.6 on 2025-09-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0002_remove_request_expected_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programrepairphase',
            name='request',
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hintgenerationphase',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.request'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.request', unique=True),
        ),
        migrations.CreateModel(
            name='ProgramEnhancementPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('model_id', models.CharField(max_length=100)),
                ('model_temperature', models.FloatField()),
                ('model_n', models.IntegerField()),
                ('whole_llm_response', models.TextField()),
                ('llm_waiting_seconds', models.FloatField()),
                ('n_correct_enhancements', models.IntegerField(null=True)),
                ('best_enhanced_program', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.request')),
            ],
        ),
        migrations.CreateModel(
            name='EnhancedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhanced_program', models.TextField()),
                ('is_correct', models.BooleanField(null=True)),
                ('program_output', models.TextField(null=True)),
                ('run_time', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.programenhancementphase')),
            ],
        ),
        migrations.DeleteModel(
            name='ProgramRepair',
        ),
        migrations.DeleteModel(
            name='ProgramRepairPhase',
        ),
    ]
