# Generated by Django 5.2.6 on 2025-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0003_remove_programrepairphase_request_request_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='explanation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
