# Generated by Django 5.2.6 on 2025-09-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0004_hint_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='generation_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.request'),
        ),
    ]
