# Generated by Django 5.2.6 on 2025-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0005_hint_generation_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='student_notebook',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
