"""
Django settings for backend_problem_handler project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import datetime
import os
from pathlib import Path
import importlib.util as _importlib_util
import importlib as _importlib
import dj_database_url

_dotenv_spec = _importlib_util.find_spec("dotenv")
if _dotenv_spec is not None:
    load_dotenv = _importlib.import_module("dotenv").load_dotenv  # type: ignore[attr-defined]
else:
    def load_dotenv(*args, **kwargs):  # type: ignore[no-redef]
        return False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect container runtime and avoid loading .env.local to prevent localhost overrides
IN_DOCKER = os.getenv("IN_DOCKER", "").lower() in ("1", "true", "yes", "t")
if not IN_DOCKER:
    if (BASE_DIR / ".env.local").exists():
        load_dotenv(BASE_DIR / ".env.local")
    elif (BASE_DIR / ".env").exists():
        load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

"""
Settings pay attention to .env.local first, then .env, and fall back to environment.
We provide a dev-only SECRET_KEY fallback when DEBUG is True.
"""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes", "t")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-insecure-secret-key"
    else:
        raise RuntimeError("DJANGO_SECRET_KEY must be set when DEBUG is False")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").replace(" ", ",").split(",") if os.getenv("DJANGO_ALLOWED_HOSTS") else []

# CSRF trusted origins (comma or space separated)
_csrf_env = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS")
CSRF_TRUSTED_ORIGINS = _csrf_env.replace(" ", ",").split(",") if _csrf_env else []

# -----------------------------
# CORS (Development Convenience)
# -----------------------------
# CORS (Development Convenience)
_cors_env = os.getenv("DJANGO_CORS_ALLOWED_ORIGINS")
CORS_ALLOWED_ORIGINS = _cors_env.replace(" ", ",").split(",") if _cors_env else []
# Alternatively, to allow everything during rapid prototyping (commented):
# CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'query',
    'execution',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_problem_handler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_problem_handler.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER') or os.getenv('DB_USERNAME'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'CONN_MAX_AGE': 60,
    }
}

_db_url = os.getenv("PROB_BACKEND_DATABASE_URL") or os.getenv("DATABASE_URL")
if _db_url:
    DATABASES['default'] = dj_database_url.parse(_db_url, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging
LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)

LOG_FILE_PREFIX = os.getenv("LOG_FILE_PREFIX", "")
APP_START_TIME = os.environ.setdefault(
    "APP_START_TIME", datetime.now().strftime("%Y%m%d_%H%M%S")
)
LOG_FILENAME = f"{LOG_FILE_PREFIX}django_{APP_START_TIME}.log"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(LOG_DIR / LOG_FILENAME),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'pika': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}


# Programming task configs
PROGRAMMING_TASK_CONFIGS_BASE = BASE_DIR / "user_customizable_configs/programming_tasks"
PROGRAMMING_TASK_CONFIGS_TASK_METADATA = PROGRAMMING_TASK_CONFIGS_BASE / "task_metadata.yaml"
PROGRAMMING_TASK_CONFIGS_TASK_DESCRIPTIONS = PROGRAMMING_TASK_CONFIGS_BASE / "task_descriptions"
PROGRAMMING_TASK_CONFIGS_TEMPLATE_CODE = PROGRAMMING_TASK_CONFIGS_BASE / "template_code"
PROGRAMMING_TASK_CONFIGS_TEST_TEMPLATES = PROGRAMMING_TASK_CONFIGS_BASE / "test_templates"
PROGRAMMING_TASK_CONFIGS_TEST_CASES = PROGRAMMING_TASK_CONFIGS_BASE / "test_cases"
PROGRAMMING_TASK_CONFIGS_EXECUTION_BOXES = PROGRAMMING_TASK_CONFIGS_BASE / "execution_boxes"