# Generated by Django 5.2.6 on 2025-09-09 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_hint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.CharField(blank=True, max_length=100, null=True)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('queuing_index', models.IntegerField(blank=True, null=True)),
                ('request_dispatched', models.BooleanField(default=False)),
                ('request_dispatched_time', models.DateTimeField(blank=True, null=True)),
                ('request_fulfilled', models.BooleanField(default=False)),
                ('TA_id', models.CharField(blank=True, max_length=100, null=True)),
                ('TA_feedback', models.TextField(blank=True, null=True)),
                ('TA_feedback_time', models.DateTimeField(blank=True, null=True)),
                ('ai_hint_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_feedbacks', to='ai_hint.aihintrequest')),
            ],
        ),
    ]
