# Generated by Django 5.2.6 on 2025-09-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0003_aihintrequest_ai_hint_aih_student_57242e_idx_and_more'),
        ('instructor_feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.CharField(blank=True, max_length=100, null=True)),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('queuing_index', models.IntegerField(blank=True, null=True)),
                ('request_dispatched', models.BooleanField(default=False)),
                ('request_dispatched_time', models.DateTimeField(blank=True, null=True)),
                ('request_fulfilled', models.BooleanField(default=False)),
                ('instructor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('instructor_feedback', models.TextField(blank=True, null=True)),
                ('instructor_feedback_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_hint_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_hint.aihintrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='TAFeedback',
        ),
    ]
