# Generated by Django 5.2.6 on 2025-09-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_feedback', '0002_instructorfeedback_delete_tafeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorfeedback',
            name='queuing_index',
        ),
        migrations.RemoveField(
            model_name='instructorfeedback',
            name='request_dispatched',
        ),
    ]
