# Generated by Django 5.2.6 on 2025-09-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_feedback', '0003_remove_instructorfeedback_queuing_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorfeedback',
            name='feedback_rated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorfeedback',
            name='is_feedback_helpful',
            field=models.BooleanField(null=True),
        ),
    ]
