# Generated by Django 5.2.6 on 2025-09-09 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIHintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_id', models.CharField(max_length=100)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hint_type', models.CharField(max_length=20)),
                ('student_program', models.TextField()),
                ('other_input_data', models.TextField(blank=True, null=True)),
                ('reflection_question', models.TextField(blank=True, null=True)),
                ('reflection_answer', models.TextField(blank=True, null=True)),
                ('reflection_time', models.DateTimeField(blank=True, null=True)),
                ('job_finished_successfully', models.BooleanField(null=True)),
                ('generation_error_message', models.TextField(blank=True, null=True)),
                ('returned_hint', models.TextField(blank=True, null=True)),
                ('returned_time', models.DateTimeField(blank=True, null=True)),
                ('other_hint_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['problem_id'], name='ai_hint_aih_problem_58cbfb_idx'), models.Index(fields=['request_time'], name='ai_hint_aih_request_c8067f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackAIHintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_returned', models.BooleanField(default=False)),
                ('returned_time', models.DateTimeField(auto_now_add=True)),
                ('original_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_requests', to='ai_hint.aihintrequest')),
            ],
        ),
    ]
