# Generated by Django 5.2.6 on 2025-09-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aihintrequest',
            name='ai_hint_aih_request_c8067f_idx',
        ),
        migrations.RemoveField(
            model_name='aihintrequest',
            name='request_time',
        ),
        migrations.AlterField(
            model_name='aihintrequest',
            name='other_hint_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='aihintrequest',
            name='other_input_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddIndex(
            model_name='aihintrequest',
            index=models.Index(fields=['created_at'], name='ai_hint_aih_created_031868_idx'),
        ),
    ]
