# Generated by Django 5.2.6 on 2025-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0002_remove_aihintrequest_ai_hint_aih_request_c8067f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aihintrequest',
            index=models.Index(fields=['student_id'], name='ai_hint_aih_student_57242e_idx'),
        ),
        migrations.AddIndex(
            model_name='aihintrequest',
            index=models.Index(fields=['hint_type'], name='ai_hint_aih_hint_ty_b5a16f_idx'),
        ),
    ]
