# Generated by Django 5.2.6 on 2025-09-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0003_aihintrequest_ai_hint_aih_student_57242e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihintrequest',
            name='hint_rated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aihintrequest',
            name='is_hint_helpful',
            field=models.BooleanField(null=True),
        ),
    ]
