# Generated by Django 5.2.6 on 2025-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0004_aihintrequest_hint_rated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihintrequest',
            name='student_notebook',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
