# Generated by Django 5.2.6 on 2025-10-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hint', '0005_aihintrequest_student_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihintrequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
