# Generated by Django 5.2.6 on 2025-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(db_index=True, max_length=255)),
                ('output', models.TextField(blank=True, null=True)),
                ('correctness', models.BooleanField(blank=True, null=True)),
                ('elapsed_time', models.FloatField(blank=True, null=True)),
                ('is_success', models.BooleanField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
